sudo: false

language: c

matrix:
  include:
    - env: GHCVER=7.6.3 CABALVER=1.24
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.6.3
            - cabal-install-1.24
    - env: GHCVER=7.8.4 CABALVER=1.24
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.8.4
            - cabal-install-1.24
    - env: GHCVER=7.10.3 CABALVER=1.24
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.3
            - cabal-install-1.24
    - env: GHCVER=8.0.2 CABALVER=1.24
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - cabal-install-1.24
    - env: GHCVER=8.2.1 CABALVER=1.24
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.2.1
            - cabal-install-1.24
    - env: GHCVER=8.4.1 CABALVER=head GHCHEAD=true
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.4.1
            - cabal-install-head
  allow_failures:
    - env: GHCVER=8.4.1 CABALVER=head GHCHEAD=true

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - ALLOW_NEWER=''
  - if ${GHCHEAD-false} ; then ALLOW_NEWER='--allow-newer' ; fi
  - cabal install --enable-tests --only-dep $ALLOW_NEWER

script:
  - WERROR='--ghc-options=-Werror'
  - if ${GHCHEAD-false} ; then WERROR='' ; fi
  - (cd ghci-wrapper && cabal configure --enable-tests $WERROR && cabal build && cabal test)
  - cabal configure --enable-tests $WERROR && cabal build && cabal test
